global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'service-abonnement'
    static_configs:
      - targets: ['service-abonnement:8082']
    metrics_path: '/actuator/prometheus'
