spring.application.name=service-billetterie
server.port=${SERVER_PORT:8081}

# Database
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/billetterie_db}
spring.data.mongodb.auto-index-creation=true

# Kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Payment Service
payment.service.url=${PAYMENT_SERVICE_URL:http://localhost:8086}

# Coordination microservice
coordination-service.url=${COORDINATION_SERVICE_URL:http://localhost:8084}