apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  labels:
    app: notification-service
data:
  # Base de donnees (service K8s MySQL interne)
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-notification:3306/notifications_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_USERNAME: "sgitu"
  
  # Kafka (service K8s Kafka interne)
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-broker:9092"
  SPRING_KAFKA_CONSUMER_GROUP_ID: "notification-group"
  
  # Mail SMTP non-sensible
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_PROTOCOL: "smtp"
  SPRING_MAIL_FROM: "tafraouti.sanae1@gmail.com"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"

  # Divers
  SPRING_PROFILES_ACTIVE: "prod"
  FIREBASE_CREDENTIALS_PATH: "/app/firebase-adminsdk.json"
